//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class GoodsOrderDetails
{
    public string OrderID { get; set; }
    public int GoodsID { get; set; }
    public short Quantity { get; set; }
    public Nullable<decimal> UnitPrice { get; set; }
    public string SellerID { get; set; }
    public string BuyerID { get; set; }
}

public partial class MemberData
{
    public MemberData()
    {
        this.StdntGoods = new HashSet<StdntGoods>();
    }

    public string MemberID { get; set; }
    public string Password { get; set; }
    public string MemberName { get; set; }
    public string ROCID { get; set; }
    public bool Gender { get; set; }
    public byte[] MemberPhoto { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string SchoolID { get; set; }
    public bool PhoneChecked { get; set; }
    public bool EmailChecked { get; set; }
    public System.DateTime RegrDateTime { get; set; }

    public virtual SchoolData SchoolData { get; set; }
    public virtual ICollection<StdntGoods> StdntGoods { get; set; }
}

public partial class ProductOrder
{
    public string OrderID { get; set; }
    public string MemberID { get; set; }
    public Nullable<System.DateTime> TransDateTime { get; set; }
    public Nullable<byte> OrderStatus { get; set; }
    public Nullable<System.DateTime> HandleTime { get; set; }
}

public partial class SchoolData
{
    public SchoolData()
    {
        this.MemberData = new HashSet<MemberData>();
    }

    public string SchoolID { get; set; }
    public string SchoolName { get; set; }
    public string Region { get; set; }

    public virtual ICollection<MemberData> MemberData { get; set; }
}

public partial class ShopData
{
    public ShopData()
    {
        this.ShopGoods = new HashSet<ShopGoods>();
    }

    public string ShopID { get; set; }
    public string Password { get; set; }
    public string ShopName { get; set; }
    public string ShopOwner { get; set; }
    public string ROCID { get; set; }
    public string BusinessNo { get; set; }
    public string Phone { get; set; }
    public string Email { get; set; }
    public string ShopAddress { get; set; }
    public string ShopArea { get; set; }
    public System.DateTime RegrDateTime { get; set; }

    public virtual ICollection<ShopGoods> ShopGoods { get; set; }
}

public partial class ShopGoods
{
    public ShopGoods()
    {
        this.ShopGoodsPic = new HashSet<ShopGoodsPic>();
    }

    public int GoodsID { get; set; }
    public string GoodsName { get; set; }
    public string SubCategoryID { get; set; }
    public string ShopID { get; set; }
    public string BuyerID { get; set; }
    public decimal Price { get; set; }
    public short Quantity { get; set; }
    public string Description { get; set; }
    public System.DateTime StartTime { get; set; }
    public Nullable<System.DateTime> EndTime { get; set; }
    public bool OnlineStatus { get; set; }
    public Nullable<System.DateTime> DealTime { get; set; }
    public int ClickCount { get; set; }
    public int TrackCount { get; set; }
    public bool Report { get; set; }

    public virtual ShopData ShopData { get; set; }
    public virtual ShopGoodsSubCategory ShopGoodsSubCategory { get; set; }
    public virtual ICollection<ShopGoodsPic> ShopGoodsPic { get; set; }
}

public partial class ShopGoodsCategory
{
    public ShopGoodsCategory()
    {
        this.ShopGoodsSubCategory = new HashSet<ShopGoodsSubCategory>();
    }

    public string CategoryID { get; set; }
    public string CategoryName { get; set; }
    public string Description { get; set; }
    public byte[] CategoryPic { get; set; }

    public virtual ICollection<ShopGoodsSubCategory> ShopGoodsSubCategory { get; set; }
}

public partial class ShopGoodsPic
{
    public int PictureID { get; set; }
    public int GoodsID { get; set; }
    public byte[] Picture { get; set; }
    public string MIMEType { get; set; }

    public virtual ShopGoods ShopGoods { get; set; }
}

public partial class ShopGoodsSubCategory
{
    public ShopGoodsSubCategory()
    {
        this.ShopGoods = new HashSet<ShopGoods>();
    }

    public string SubCategoryID { get; set; }
    public string CategoryID { get; set; }
    public string SubCategoryName { get; set; }
    public string Description { get; set; }
    public byte[] SubCategoryPic { get; set; }

    public virtual ICollection<ShopGoods> ShopGoods { get; set; }
    public virtual ShopGoodsCategory ShopGoodsCategory { get; set; }
}

public partial class StdntGoods
{
    public StdntGoods()
    {
        this.StdntGoodsPic = new HashSet<StdntGoodsPic>();
    }

    public int GoodsID { get; set; }
    public string GoodsName { get; set; }
    public string SubCategoryID { get; set; }
    public string SellerID { get; set; }
    public string BuyerID { get; set; }
    public decimal Price { get; set; }
    public Nullable<decimal> ShippingCost { get; set; }
    public short Quantity { get; set; }
    public string Description { get; set; }
    public System.DateTime StartTime { get; set; }
    public Nullable<System.DateTime> EndTime { get; set; }
    public bool OnlineStatus { get; set; }
    public Nullable<System.DateTime> DealTime { get; set; }
    public int ClickCount { get; set; }
    public int TrackCount { get; set; }
    public bool IsExchange { get; set; }
    public bool SecondHand { get; set; }
    public bool Report { get; set; }

    public virtual MemberData MemberData { get; set; }
    public virtual StdntGoodsSubCategory StdntGoodsSubCategory { get; set; }
    public virtual ICollection<StdntGoodsPic> StdntGoodsPic { get; set; }
}

public partial class StdntGoodsCategory
{
    public StdntGoodsCategory()
    {
        this.StdntGoodsSubCategory = new HashSet<StdntGoodsSubCategory>();
    }

    public string CategoryID { get; set; }
    public string CategoryName { get; set; }
    public string Description { get; set; }
    public byte[] CategoryPic { get; set; }

    public virtual ICollection<StdntGoodsSubCategory> StdntGoodsSubCategory { get; set; }
}

public partial class StdntGoodsPic
{
    public int PictureID { get; set; }
    public int GoodsID { get; set; }
    public byte[] Picture { get; set; }
    public string MIMEType { get; set; }

    public virtual StdntGoods StdntGoods { get; set; }
}

public partial class StdntGoodsSubCategory
{
    public StdntGoodsSubCategory()
    {
        this.StdntGoods = new HashSet<StdntGoods>();
    }

    public string SubCategoryID { get; set; }
    public string CategoryID { get; set; }
    public string SubCategoryName { get; set; }
    public string Description { get; set; }
    public byte[] SubCategoryPic { get; set; }

    public virtual StdntGoodsCategory StdntGoodsCategory { get; set; }
    public virtual ICollection<StdntGoods> StdntGoods { get; set; }
}

public partial class StdntGoodsView
{
    public string GoodsName { get; set; }
    public decimal Price { get; set; }
    public short Quantity { get; set; }
    public string SellerID { get; set; }
    public System.DateTime StartTime { get; set; }
    public byte[] Picture { get; set; }
    public int PictureID { get; set; }
    public string SchoolName { get; set; }
    public string Region { get; set; }
    public string Description { get; set; }
    public int GoodsID { get; set; }
}

public partial class WishDetail
{
    public int DetailID { get; set; }
    public int WishID { get; set; }
    public int GoodsID { get; set; }
    public string Comment { get; set; }
    public int HopeQuantity { get; set; }
    public int HaveQuantity { get; set; }
    public int Priority { get; set; }
    public System.DateTime DateAdd { get; set; }
    public string GoodsName { get; set; }
    public string SellerID { get; set; }
    public Nullable<decimal> Price { get; set; }
    public Nullable<int> Quantity { get; set; }
    public byte[] Picture { get; set; }
}

public partial class WishList
{
    public int WishID { get; set; }
    public string WishName { get; set; }
    public string MemberID { get; set; }
    public bool DefaultList { get; set; }
    public bool SecuritySet { get; set; }
    public bool Surprise { get; set; }
    public string Address { get; set; }
    public string AboutMe { get; set; }
}
